env:
  global:
    secure: PBuds6kkJpIw7ICwVJ3nYzDtxVfTlBNCR4WQovYjn6aryoTuyv3+xtPoSxzdvJDj/G/gsNfUeGsXC3x9qDC/wfMsNpc6gFbksMNXbhc2O/ndjL0YI1rY4pIDdU76lVU+cstBQYF0kNqwU8fh4Yzp6VeAUTUxSluHVFJDol5VCA0=
branches:
  only:
    - source
language: python
python:
  - 2.7
install:
  - pip install pelican rembed-markdown
before_script:
  - git clone https://github.com/rembed/rembed.github.io.git output
script:
  - pelican content -s publishconf.py
after_success:
  - git config credential.helper "store --file=output/.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > output/.git/credentials
  - cd output && git push origin master
