sudo: false
env:
  global:
    secure: TJg9T8wFNSfxk19Bciv7UDpXZyuZA4uiebwwegQSxuM0Z74PE0L3Ko/AXhnCOyBpth4rONI4yYWSl/e/c9OPlAEG4z+PXW+nz7CYv1dUdb/pqGvU6nsUPgE+oHaDdsUIyUyM+FLDdd7GDf3fDz3jLS2E9M2EWjq59BGXTibUCdw=
branches:
  only:
    - source
language: python
python:
  - 2.7
install:
  - pip install pelican pyembed-markdown pyembed-rst
before_script:
  - git clone https://github.com/pyembed/pyembed.github.io.git output
script:
  - pelican content -s publishconf.py
after_success:
  - cd output
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - git add .
  - git commit -m "Updating site"
  - git push "https://${GH_TOKEN}@github.com/pyembed/pyembed.github.io.git" master > /dev/null 2>&1
