env:
  secure: HyuPY4bB7ytlqYbCrNpUStEjLs16jR619PQCn1mjwA+T0RkaDYVYHeGm6HMy6mfRYc/CX9o6fz1bDp1UIdzuLx/NhUnB7t5ykNqWBX7+QOrpLyEJQXIDyn9xI6BGkXrRfzCImqiH02jOr+vWT8WRXyHcuT45EwMDuXtr4a3sgYo=
branches:
  only:
  - source
language: python
python:
  - 2.7
install:
  - pip install pelican pyembed-markdown
before_script:
  - git clone https://github.com/pyembed/pyembed.github.io.git output
script:
  - pelican content -s publishconf.py
after_success:
  - cd output
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - git add .
  - git commit -m "Updating site"
  - git push "https://${GH_TOKEN}:@github.com" master
