env:
  global:
    secure: IfyAsjOthEuS5QbbYslKWA1CldZD8WWMfS+iBc7m7gf8/kyBBg0PWsFVJ8phFzweBY/1oRz6FwTu46U48HYcEqtWhcR3zZ3DYmiaJJESvXOL++Bc00pq5fkILMEy53t1Vvnlpof/ZAADkyrvWA9gBpzBflsdAdnc5Fxs5BqYrgc=
branches:
  only:
    - source
language: python
python:
  - 2.7
install:
  - pip install pelican pyembed-markdown
before_script:
  - git clone https://github.com/pyembed/pyembed.github.io.git output
script:
  - pelican content -s publishconf.py
after_success:
  - cd output
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add .
  - git commit -m "Updating site"
  - git push origin master
